import React from 'react';
import DocumentMeta from 'react-document-meta';
import './Cookies.scss';
import {appPages} from './../../api/appData';

import Page from './../../components/Page/Page';


export default function Choreography (){

    return(
        <DocumentMeta {...appPages.cookies.meta}>
            <div className="Cookies">
                <Page data = {appPages.cookies.topContent}>
                        {/* <CookiesNav/> */}
                        <CookiesBody/>
                </Page>
            </div>
        </DocumentMeta>
    )
}

function CookiesNav(){
    return(
        <section className="Cookies__nav">
                <a href="#intro">1. Introduction.</a>
                <a href="#about">2. What are cookies?</a>
                <a href="#use">3. How we use cookies?</a>
                <a href="#third-parties">4. Third-party cookies.</a>
                <a href="#choice">5. What are your choices regarding cookies?</a>

        </section>
    )
}
function CookiesBody(){
    return(
        <section className="Cookies__body">
                <div id="intro">
                    <p className="color_themed"><b>Please read this Cookie Policy carefully before you start to use our Website ("the Service"). <br/> By continuing to use the Service you agree to our use of cookies as set out in this Policy.</b></p>
                    <p>Our Cookies Policy explains what cookies are, how we use cookies, how third-parties we may partner with may use cookies on this website and your choices regarding cookies.</p>
                </div>
                <div id="about">
                    <p><b>What are cookies?</b></p>
                    <p>Cookies are small pieces of text sent by your web browser by a website you visit. A cookie file is stored in your web browser and allows the Service or a third-party to recognize you and make your next visit easier and the Service more useful to you.</p>
                </div>
                <div id="use">
                    <p><b>How we use cookies?</b></p>
                    <p>When you use and access the Service, we may place a number of cookies files in your web browser.</p>
                    <p>We use cookies for the following purposes: to enable certain functions of the Service, to provide analytics and store your preferences.</p>
                    <p>We use both session and persistent cookies on the Service.<br/>

                </p>
            </div>
            <div id="third-parties">
                <p><b>Third-party cookies.</b></p>
                <p>In addition to our own cookies, the Service may also use various third-parties cookies to report usage statistics of the Service.</p>
                <p>The Service uses Google Analytics, a web analytics service provided by Google. Google Analytics uses ‘cookies’ to help the website analyse how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States. The IP address will be truncated before transmission. On our behalf Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity and providing other services relating to website activity and internet activity in connection with the use of the website. Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser.</p>
                <div className="cookies__list">
                    <b>GOOGLE ANALYTICS COOKIES</b> <br/>
                    <span>
                        ___ga <br/>
                        ___gid <br/>
                        ___gat <br/>
                        __utma <br/>
                        __utmb <br/>
                        __utmc <br/>
                        __utmz <br/>
                        ___utmv <br/> 
                    </span>
                    The Service uses all of the cookies above. <br/>
                    Various duration: a mix of session and persisitent cookies lasting 30 mins, 6 months, or 1-2 yrs. Anonymously tracks use of website.  These cookies are set or updated on any page visited. See <a href="https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage"><u>here</u></a> for full details. Several cookies are set but all serve the same purpose: to see how people reached the site and used it, including search terms used and referring sites.
            </div>
            </div>
            <div id="choice">
                <p><b>What are your choices regarding cookies?</b></p>
                <p>If you'd like to delete cookies or instruct your web browser to delete or refuse cookies, please visit the help pages of your web browser.</p>
                <p>Please note, however, that if you delete cookies or refuse to accept them, you might not be able to use all of the features we offer, you may not be able to store your preferences, and some of our pages might not display properly.</p>
            </div>

        </section>
    )
}
